---
- name: mysql directory
  file:
    path: /home/backup/mysql
    state: directory
    owner: backup
    group: backup
    mode: '0774'

- name: MySql user for backup
  mysql_user:
    name: "{{mysql_user_backup}}"
    password: "{{mysql_backup_pw}}"
    priv: '{{mysql_database}}.*:LOCK TABLES,SELECT'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: cp conf
  template:
    src: .my.cnf.j2
    dest: /home/backup/.my.cnf
    owner: backup
    group: backup
    force: yes
    mode: '0600'

- name: Cronjob cp
  template:
    src: mysql-backup.j2
    dest: /etc/cron.d/mysql-backup
    force: yes
    mode: '0644'