---
- name: Download influxstats exporter
  get_url:
    url: https://github.com/carlpett/influxdb_stats_exporter/releases/download/v0.1.1/influx_stats_exporter_darwin_amd64
    dest: /usr/local/bin/influxdb-stats-exporter
    mode: '0777' # Failed at step EXEC spawning /usr/local/bin/influxexporter: Permission denied
    owner: prometheus

- name: Env file
  template:
    src: influx-env.j2
    dest: /etc/default/influx-env
  notify:
    - daemon-reload
    - restart

- name: CP Service
  template:
    src: influxdb-stats-exporter.service.j2
    dest: /etc/systemd/system/influxdb-stats-exporter.service
    owner: prometheus
  notify:
    - daemon-reload
    - restart

- name: Enable exporter
  service:
    name: influxdb-stats-exporter
    state: started
    enabled: yes