---
- name: ensure ryslog is installed
  apt:
    name: rsyslog
    state: latest

- name: copy configuration
  template:
    src: telegraf-syslog.conf.j2
    dest: /etc/rsyslog.d/telegraf.conf
  notify: restarted

- name: enable rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes