---
- name: grafana required pkg
  apt:
    name:
      - adduser
      - libfontconfig1

- name: download grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_9.3.1_amd64.deb
    dest: /tmp/grafana_9.3.1_amd64.deb

- name: install grafana
  apt:
    deb: /tmp/grafana_9.3.1_amd64.deb

- name: Grafana config
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify:
    - restart

- name: Enabled
  service:
    name: grafana-server
    state: started
    enabled: yes