---
- name: Create the grafana user
  ansible.builtin.user:
    name: grafana
    uid: 472
    state: present

- name: folder with correct permissions datasources
  file:
    name: /opt/docker/grafana/provisioning/datasources
    state: directory
    recurse: yes #gives permissions for subfolders also

- name: folder with correct permissions dashboards
  file:
    name: /opt/docker/grafana/provisioning/dashboards
    state: directory
    recurse: yes #gives permissions for subfolders also





- name: Config
  template:
    src: grafana.ini.j2
    dest: /opt/docker/grafana/grafana.ini
  notify:
    - stop
    - start
  no_log: True

- name: Datasources
  template:
    src: default.yaml.j2
    dest: /opt/docker/grafana/provisioning/datasources/default.yaml
  notify:
    - stop
    - start

- name: dashboards yaml
  template:
    src: sample.yaml.j2
    dest: /opt/docker/grafana/provisioning/dashboards/default.yaml
  notify:
    - stop
    - start

- name: copy dashboards
  copy:
    src: "{{ item }}"
    dest: /opt/docker/grafana/provisioning/dashboards
  with_fileglob:
    - ../files/*.json
  notify:
    - stop
    - start






- name: grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    env:
      GF_SERVER_ROOT_URL: "http://{{ ansible_host }}:{{ ansible_port // 100 }}80/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - /opt/docker/grafana:/etc/grafana #cp local:docker
    ports:
      - "{{docker_grafana_port}}:3000"
    restart_policy: always