- name: Install uwsgi
  apt:
    name: uwsgi
    state: latest

- name: Install uwsgi python plugin
  apt:
    name: uwsgi-plugin-python3
    state: latest

- name: Copy configuration file and restart uwsgi
  template:
    src: ../templates/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uwsgi

- name: Start uwsgi
  service:
    name: uwsgi
    state: started
    enabled: yes
  become: yes