{
 "title": "Main",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "node_memory_Active_bytes/node_memory_MemTotal_bytes*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU usage %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "rate(node_cpu_seconds_total{mode=\"idle\"}[1m])*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HaProxy UP",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "haproxy_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Haproxy Server Up",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "haproxy_server_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bind Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "bind_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Total Bind Queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      { "expr": "bind_resolver_queries_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Keepalived UP",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "keepalived_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "VRRP State",
     "type": "stat",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "keepalived_vrrp_state", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "NGINX Status",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "nginx_up", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rtt",
       "select": [
        [
         { "params": [ "rtt" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Node Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"linux\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Expoter Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"haproxy\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"keepalived\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bind9 Exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"bind9\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"influxdb\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PRM Exporter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}