- name: directory for agama
  file:
    name: /opt/agama
    state: directory
    recurse: true

#https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile

- name: agama dockerfile
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/Dockerfile
    dest: /opt/agama

- name: Get agama
  get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama

- name: agama docker image build
  docker_image:
    name: agama
    source: build
    build:
      path: /opt/agama

- name: start agama container
  docker_container:
    name: agama
    image: agama
    env:
      AGAMA_DATABASE_URI: "mysql+pymysql://{{mysql_user}}:{{mysql_password}}@{{mysql_host}}/{{mysql_database}}"
    ports: 5000:8000
    restart_policy: always