---
- name: backup user
  ansible.builtin.user:
    name: backup
    generate_ssh_key: yes
    ssh_key_file: /home/backup/.ssh/id_rsa
    create_home: yes
    home: /home/backup


- name: copy known hosts
  template:
    src: known_hosts.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0774'

- name: restore directory
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    mode: '0774'

- name: ensure duplicity is installed
  apt:
    name: duplicity
    state: latest