---
- name: Copy config
  template:
    src: my.cnf.j2
    dest: /var/lib/prometheus/.my.cnf
  notify: restart
  no_log: yes

- name: Copy prometheus conf
  template:
    src: prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
  notify: restart

- name: mysql exporter installed
  apt:
    name: prometheus-mysqld-exporter
    state: latest

- name: start mysql exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes