---
- name: Bind exporter installed
  apt:
    name: prometheus-bind-exporter
    state: latest

- name: Enable bind exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes