---
- name: ensure keepalived installed
  apt:
    name: keepalived
    state: latest

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify:
    - restart
    - restart haproxy

- name: download and unzip keepalived exporter
  unarchive:
    src: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: start keepalived
  template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
  notify:
    - daemon-reload
    #- restart keepalived-exporter
    - restart haproxy

- name: enable keepalived
  service:
    name: keepalived
    state: started
    enabled: yes

#- name: enable keepalived-exporter
 # service:
  #  name: keepalived-exporter
   # state: started
    #enabled: yes