- name: install bind9
  apt:
    name: bind9
    state: latest

- name: start bind9
  service:
    name: bind9
    state: started
    enabled: yes

- name: Copy config
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Copy master zone config
  template:
    src: ../templates/db.dok.j2
    dest: /var/lib/bind/db.infra.rd
  notify: restart bind9

- name: C
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: restart bind9