- name: install bind9
  apt:
    name: bind9
    state: latest

- name: start bind9
  service:
    name: bind9
    state: started
    enabled: yes

- name: Copy config
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Copy master zone config
  template:
    src: ../templates/db.dok.j2
    dest: /var/lib/bind/db.dok
  notify: Restart bind9